In [1]:
using LinearAlgebra

---

# LU

In [4]:
A = [
    3 9 1
    4 7 0
    1 5 2.0
]

3×3 Array{Float64,2}:
 3.0  9.0  1.0
 4.0  7.0  0.0
 1.0  5.0  2.0

In [5]:
A = Float64[3 9 1; 4 7 0; 1 5 2]

3×3 Array{Float64,2}:
 3.0  9.0  1.0
 4.0  7.0  0.0
 1.0  5.0  2.0

In [29]:
?lu

search: lu lu! LU flush values include include_string include_dependency lmul!



```
lu(A, pivot=Val(true); check = true) -> F::LU
```

Compute the LU factorization of `A`.

When `check = true`, an error is thrown if the decomposition fails. When `check = false`, responsibility for checking the decomposition's validity (via [`issuccess`](@ref)) lies with the user.

In most cases, if `A` is a subtype `S` of `AbstractMatrix{T}` with an element type `T` supporting `+`, `-`, `*` and `/`, the return type is `LU{T,S{T}}`. If pivoting is chosen (default) the element type should also support [`abs`](@ref) and [`<`](@ref).

The individual components of the factorization `F` can be accessed via [`getproperty`](@ref):

| Component | Description                         |
|:--------- |:----------------------------------- |
| `F.L`     | `L` (lower triangular) part of `LU` |
| `F.U`     | `U` (upper triangular) part of `LU` |
| `F.p`     | (right) permutation `Vector`        |
| `F.P`     | (right) permutation `Matrix`        |

Iterating the factorization produces the components `F.L`, `F.U`, and `F.p`.

The relationship between `F` and `A` is

`F.L*F.U == A[F.p, :]`

`F` further supports the following functions:

| Supported function  | `LU` | `LU{T,Tridiagonal{T}}` |
|:------------------- |:---- |:---------------------- |
| [`/`](@ref)         | ✓    |                        |
| [`\`](@ref)         | ✓    | ✓                      |
| [`inv`](@ref)       | ✓    | ✓                      |
| [`det`](@ref)       | ✓    | ✓                      |
| [`logdet`](@ref)    | ✓    | ✓                      |
| [`logabsdet`](@ref) | ✓    | ✓                      |
| [`size`](@ref)      | ✓    | ✓                      |

# Examples

```jldoctest
julia> A = [4 3; 6 3]
2×2 Array{Int64,2}:
 4  3
 6  3

julia> F = lu(A)
LU{Float64,Array{Float64,2}}
L factor:
2×2 Array{Float64,2}:
 1.0       0.0
 0.666667  1.0
U factor:
2×2 Array{Float64,2}:
 6.0  3.0
 0.0  1.0

julia> F.L * F.U == A[F.p, :]
true

julia> l, u, p = lu(A); # destructuring via iteration

julia> l == F.L && u == F.U && p == F.p
true
```

---

```
lu(A::SparseMatrixCSC; check = true) -> F::UmfpackLU
```

Compute the LU factorization of a sparse matrix `A`.

For sparse `A` with real or complex element type, the return type of `F` is `UmfpackLU{Tv, Ti}`, with `Tv` = [`Float64`](@ref) or `ComplexF64` respectively and `Ti` is an integer type ([`Int32`](@ref) or [`Int64`](@ref)).

When `check = true`, an error is thrown if the decomposition fails. When `check = false`, responsibility for checking the decomposition's validity (via [`issuccess`](@ref)) lies with the user.

The individual components of the factorization `F` can be accessed by indexing:

| Component | Description                         |
|:--------- |:----------------------------------- |
| `L`       | `L` (lower triangular) part of `LU` |
| `U`       | `U` (upper triangular) part of `LU` |
| `p`       | right permutation `Vector`          |
| `q`       | left permutation `Vector`           |
| `Rs`      | `Vector` of scaling factors         |
| `:`       | `(L,U,p,q,Rs)` components           |

The relation between `F` and `A` is

`F.L*F.U == (F.Rs .* A)[F.p, F.q]`

`F` further supports the following functions:

  * [`\`](@ref)
  * [`cond`](@ref)
  * [`det`](@ref)

!!! note
    `lu(A::SparseMatrixCSC)` uses the UMFPACK library that is part of SuiteSparse. As this library only supports sparse matrices with [`Float64`](@ref) or `ComplexF64` elements, `lu` converts `A` into a copy that is of type `SparseMatrixCSC{Float64}` or `SparseMatrixCSC{ComplexF64}` as appropriate.



In [22]:
F = lu(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0   0.0       0.0
 0.75  1.0       0.0
 0.25  0.866667  1.0
U factor:
3×3 Array{Float64,2}:
 4.0  7.0   0.0
 0.0  3.75  1.0
 0.0  0.0   1.13333

In [23]:
L = F.L

3×3 Array{Float64,2}:
 1.0   0.0       0.0
 0.75  1.0       0.0
 0.25  0.866667  1.0

In [24]:
U = F.U

3×3 Array{Float64,2}:
 4.0  7.0   0.0
 0.0  3.75  1.0
 0.0  0.0   1.13333

In [25]:
L*U

3×3 Array{Float64,2}:
 4.0  7.0  0.0
 3.0  9.0  1.0
 1.0  5.0  2.0

In [26]:
A

3×3 Array{Float64,2}:
 3.0  9.0  1.0
 4.0  7.0  0.0
 1.0  5.0  2.0

In [27]:
F.p

3-element Array{Int64,1}:
 2
 1
 3

In [28]:
A[F.p,:]

3×3 Array{Float64,2}:
 4.0  7.0  0.0
 3.0  9.0  1.0
 1.0  5.0  2.0

In [18]:
F = lu(A, Val(false))

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0        0.0  0.0
 1.33333    1.0  0.0
 0.333333  -0.4  1.0
U factor:
3×3 Array{Float64,2}:
 3.0   9.0   1.0
 0.0  -5.0  -1.33333
 0.0   0.0   1.13333

In [20]:
L = F.L
U = F.U
L*U

3×3 Array{Float64,2}:
 3.0  9.0  1.0
 4.0  7.0  0.0
 1.0  5.0  2.0

In [21]:
A

3×3 Array{Float64,2}:
 3.0  9.0  1.0
 4.0  7.0  0.0
 1.0  5.0  2.0

---

# Cholesky

In [30]:
A = rand(3, 3)

3×3 Array{Float64,2}:
 0.977753  0.0097354  0.921972
 0.953398  0.467663   0.0346951
 0.312696  0.0510857  0.481566

In [31]:
A = Symmetric(A)

3×3 Symmetric{Float64,Array{Float64,2}}:
 0.977753   0.0097354  0.921972
 0.0097354  0.467663   0.0346951
 0.921972   0.0346951  0.481566

In [32]:
A.data

3×3 Array{Float64,2}:
 0.977753  0.0097354  0.921972
 0.953398  0.467663   0.0346951
 0.312696  0.0510857  0.481566

In [33]:
A.uplo

'U': ASCII/Unicode U+0055 (category Lu: Letter, uppercase)

In [34]:
eigvals(A)

3-element Array{Float64,1}:
 -0.22578291538352752
  0.46765402969825226
  1.6851108523394958

In [35]:
A + I

3×3 Symmetric{Float64,Array{Float64,2}}:
 1.97775    0.0097354  0.921972
 0.0097354  1.46766    0.0346951
 0.921972   0.0346951  1.48157

In [36]:
eigvals(A + I)

3-element Array{Float64,1}:
 0.7742170846164727
 1.4676540296982528
 2.6851108523394958

In [37]:
A = A + I

3×3 Symmetric{Float64,Array{Float64,2}}:
 1.97775    0.0097354  0.921972
 0.0097354  1.46766    0.0346951
 0.921972   0.0346951  1.48157

In [39]:
?cholesky

search: cholesky cholesky! Cholesky CholeskyPivoted



```
cholesky(A, Val(false); check = true) -> Cholesky
```

Compute the Cholesky factorization of a dense symmetric positive definite matrix `A` and return a [`Cholesky`](@ref) factorization. The matrix `A` can either be a [`Symmetric`](@ref) or [`Hermitian`](@ref) [`StridedMatrix`](@ref) or a *perfectly* symmetric or Hermitian `StridedMatrix`. The triangular Cholesky factor can be obtained from the factorization `F` with: `F.L` and `F.U`. The following functions are available for `Cholesky` objects: [`size`](@ref), [`\`](@ref), [`inv`](@ref), [`det`](@ref), [`logdet`](@ref) and [`isposdef`](@ref).

If you have a matrix `A` that is slightly non-Hermitian due to roundoff errors in its construction, wrap it in `Hermitian(A)` before passing it to `cholesky` in order to treat it as perfectly Hermitian.

When `check = true`, an error is thrown if the decomposition fails. When `check = false`, responsibility for checking the decomposition's validity (via [`issuccess`](@ref)) lies with the user.

# Examples

```jldoctest
julia> A = [4. 12. -16.; 12. 37. -43.; -16. -43. 98.]
3×3 Array{Float64,2}:
   4.0   12.0  -16.0
  12.0   37.0  -43.0
 -16.0  -43.0   98.0

julia> C = cholesky(A)
Cholesky{Float64,Array{Float64,2}}
U factor:
3×3 UpperTriangular{Float64,Array{Float64,2}}:
 2.0  6.0  -8.0
  ⋅   1.0   5.0
  ⋅    ⋅    3.0

julia> C.U
3×3 UpperTriangular{Float64,Array{Float64,2}}:
 2.0  6.0  -8.0
  ⋅   1.0   5.0
  ⋅    ⋅    3.0

julia> C.L
3×3 LowerTriangular{Float64,Array{Float64,2}}:
  2.0   ⋅    ⋅
  6.0  1.0   ⋅
 -8.0  5.0  3.0

julia> C.L * C.U == A
true
```

---

```
cholesky(A, Val(true); tol = 0.0, check = true) -> CholeskyPivoted
```

Compute the pivoted Cholesky factorization of a dense symmetric positive semi-definite matrix `A` and return a [`CholeskyPivoted`](@ref) factorization. The matrix `A` can either be a [`Symmetric`](@ref) or [`Hermitian`](@ref) [`StridedMatrix`](@ref) or a *perfectly* symmetric or Hermitian `StridedMatrix`. The triangular Cholesky factor can be obtained from the factorization `F` with: `F.L` and `F.U`. The following functions are available for `CholeskyPivoted` objects: [`size`](@ref), [`\`](@ref), [`inv`](@ref), [`det`](@ref), and [`rank`](@ref). The argument `tol` determines the tolerance for determining the rank. For negative values, the tolerance is the machine precision.

If you have a matrix `A` that is slightly non-Hermitian due to roundoff errors in its construction, wrap it in `Hermitian(A)` before passing it to `cholesky` in order to treat it as perfectly Hermitian.

When `check = true`, an error is thrown if the decomposition fails. When `check = false`, responsibility for checking the decomposition's validity (via [`issuccess`](@ref)) lies with the user.

---

```
cholesky(A; shift = 0.0, check = true, perm = nothing) -> CHOLMOD.Factor
```

Compute the Cholesky factorization of a sparse positive definite matrix `A`. `A` must be a [`SparseMatrixCSC`](@ref) or a [`Symmetric`](@ref)/[`Hermitian`](@ref) view of a `SparseMatrixCSC`. Note that even if `A` doesn't have the type tag, it must still be symmetric or Hermitian. If `perm` is not given, a fill-reducing permutation is used. `F = cholesky(A)` is most frequently used to solve systems of equations with `F\b`, but also the methods [`diag`](@ref), [`det`](@ref), and [`logdet`](@ref) are defined for `F`. You can also extract individual factors from `F`, using `F.L`. However, since pivoting is on by default, the factorization is internally represented as `A == P'*L*L'*P` with a permutation matrix `P`; using just `L` without accounting for `P` will give incorrect answers. To include the effects of permutation, it's typically preferable to extract "combined" factors like `PtL = F.PtL` (the equivalent of `P'*L`) and `LtP = F.UP` (the equivalent of `L'*P`).

When `check = true`, an error is thrown if the decomposition fails. When `check = false`, responsibility for checking the decomposition's validity (via [`issuccess`](@ref)) lies with the user.

Setting the optional `shift` keyword argument computes the factorization of `A+shift*I` instead of `A`. If the `perm` argument is provided, it should be a permutation of `1:size(A,1)` giving the ordering to use (instead of CHOLMOD's default AMD ordering).

# Examples

In the following example, the fill-reducing permutation used is `[3, 2, 1]`. If `perm` is set to `1:3` to enforce no permutation, the number of nonzero elements in the factor is 6.

```jldoctest
julia> A = [2 1 1; 1 2 0; 1 0 2]
3×3 Array{Int64,2}:
 2  1  1
 1  2  0
 1  0  2

julia> C = cholesky(sparse(A))
SuiteSparse.CHOLMOD.Factor{Float64}
type:    LLt
method:  simplicial
maxnnz:  5
nnz:     5
success: true

julia> C.p
3-element Array{Int64,1}:
 3
 2
 1

julia> L = sparse(C.L);

julia> Matrix(L)
3×3 Array{Float64,2}:
 1.41421   0.0       0.0
 0.0       1.41421   0.0
 0.707107  0.707107  1.0

julia> L * L' ≈ A[C.p, C.p]
true

julia> P = sparse(1:3, C.p, ones(3))
3×3 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [3, 1]  =  1.0
  [2, 2]  =  1.0
  [1, 3]  =  1.0

julia> P' * L * L' * P ≈ A
true

julia> C = cholesky(sparse(A), perm=1:3)
SuiteSparse.CHOLMOD.Factor{Float64}
type:    LLt
method:  simplicial
maxnnz:  6
nnz:     6
success: true

julia> L = sparse(C.L);

julia> Matrix(L)
3×3 Array{Float64,2}:
 1.41421    0.0       0.0
 0.707107   1.22474   0.0
 0.707107  -0.408248  1.1547

julia> L * L' ≈ A
true
```

!!! note
    This method uses the CHOLMOD library from SuiteSparse, which only supports doubles or complex doubles. Input matrices not of those element types will be converted to `SparseMatrixCSC{Float64}` or `SparseMatrixCSC{ComplexF64}` as appropriate.

    Many other functions from CHOLMOD are wrapped but not exported from the `Base.SparseArrays.CHOLMOD` module.



In [41]:
F = cholesky(A)

Cholesky{Float64,Array{Float64,2}}
U factor:
3×3 UpperTriangular{Float64,Array{Float64,2}}:
 1.40633  0.00692257  0.655589
  ⋅       1.21145     0.0248931
  ⋅        ⋅          1.02526

In [42]:
R = F.U

3×3 UpperTriangular{Float64,Array{Float64,2}}:
 1.40633  0.00692257  0.655589
  ⋅       1.21145     0.0248931
  ⋅        ⋅          1.02526

In [43]:
R'*R

3×3 Array{Float64,2}:
 1.97775    0.0097354  0.921972
 0.0097354  1.46766    0.0346951
 0.921972   0.0346951  1.48157

In [44]:
A

3×3 Symmetric{Float64,Array{Float64,2}}:
 1.97775    0.0097354  0.921972
 0.0097354  1.46766    0.0346951
 0.921972   0.0346951  1.48157

In [45]:
R'R - A

3×3 Array{Float64,2}:
 2.22045e-16  0.0  1.11022e-16
 0.0          0.0  0.0
 1.11022e-16  0.0  2.22045e-16

---

# QR

In [46]:
A = rand(5, 3)

5×3 Array{Float64,2}:
 0.650341   0.478053    0.905751
 0.0423931  0.864138    0.15344
 0.68511    0.689255    0.815647
 0.417137   0.00815743  0.823906
 0.512861   0.471553    0.378009

In [47]:
?qr

search: qr qr! QR QRPivoted sqrt isqrt QuickSort PartialQuickSort



```
qr(A, pivot=Val(false); blocksize) -> F
```

Compute the QR factorization of the matrix `A`: an orthogonal (or unitary if `A` is complex-valued) matrix `Q`, and an upper triangular matrix `R` such that

$$
A = Q R
$$

The returned object `F` stores the factorization in a packed format:

  * if `pivot == Val(true)` then `F` is a [`QRPivoted`](@ref) object,
  * otherwise if the element type of `A` is a BLAS type ([`Float32`](@ref), [`Float64`](@ref), `ComplexF32` or `ComplexF64`), then `F` is a [`QRCompactWY`](@ref) object,
  * otherwise `F` is a [`QR`](@ref) object.

The individual components of the decomposition `F` can be retrieved via property accessors:

  * `F.Q`: the orthogonal/unitary matrix `Q`
  * `F.R`: the upper triangular matrix `R`
  * `F.p`: the permutation vector of the pivot ([`QRPivoted`](@ref) only)
  * `F.P`: the permutation matrix of the pivot ([`QRPivoted`](@ref) only)

Iterating the decomposition produces the components `Q`, `R`, and if extant `p`.

The following functions are available for the `QR` objects: [`inv`](@ref), [`size`](@ref), and [`\`](@ref). When `A` is rectangular, `\` will return a least squares solution and if the solution is not unique, the one with smallest norm is returned. When `A` is not full rank, factorization with (column) pivoting is required to obtain a minimum norm solution.

Multiplication with respect to either full/square or non-full/square `Q` is allowed, i.e. both `F.Q*F.R` and `F.Q*A` are supported. A `Q` matrix can be converted into a regular matrix with [`Matrix`](@ref).  This operation returns the "thin" Q factor, i.e., if `A` is `m`×`n` with `m>=n`, then `Matrix(F.Q)` yields an `m`×`n` matrix with orthonormal columns.  To retrieve the "full" Q factor, an `m`×`m` orthogonal matrix, use `F.Q*Matrix(I,m,m)`.  If `m<=n`, then `Matrix(F.Q)` yields an `m`×`m` orthogonal matrix.

The block size for QR decomposition can be specified by keyword argument `blocksize :: Integer` when `pivot == Val(false)` and `A isa StridedMatrix{<:BlasFloat}`. It is ignored when `blocksize > minimum(size(A))`.  See [`QRCompactWY`](@ref).

!!! compat "Julia 1.4"
    The `blocksize` keyword argument requires Julia 1.4 or later.


# Examples

```jldoctest
julia> A = [3.0 -6.0; 4.0 -8.0; 0.0 1.0]
3×2 Array{Float64,2}:
 3.0  -6.0
 4.0  -8.0
 0.0   1.0

julia> F = qr(A)
LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.6   0.0   0.8
 -0.8   0.0  -0.6
  0.0  -1.0   0.0
R factor:
2×2 Array{Float64,2}:
 -5.0  10.0
  0.0  -1.0

julia> F.Q * F.R == A
true
```

!!! note
    `qr` returns multiple types because LAPACK uses several representations that minimize the memory storage requirements of products of Householder elementary reflectors, so that the `Q` and `R` matrices can be stored compactly rather as two separate dense matrices.


---

```
qr(A) -> QRSparse
```

Compute the `QR` factorization of a sparse matrix `A`. Fill-reducing row and column permutations are used such that `F.R = F.Q'*A[F.prow,F.pcol]`. The main application of this type is to solve least squares or underdetermined problems with [`\`](@ref). The function calls the C library SPQR.

!!! note
    `qr(A::SparseMatrixCSC)` uses the SPQR library that is part of SuiteSparse. As this library only supports sparse matrices with [`Float64`](@ref) or `ComplexF64` elements, as of Julia v1.4 `qr` converts `A` into a copy that is of type `SparseMatrixCSC{Float64}` or `SparseMatrixCSC{ComplexF64}` as appropriate.


# Examples

```jldoctest
julia> A = sparse([1,2,3,4], [1,1,2,2], [1.0,1.0,1.0,1.0])
4×2 SparseMatrixCSC{Float64,Int64} with 4 stored entries:
  [1, 1]  =  1.0
  [2, 1]  =  1.0
  [3, 2]  =  1.0
  [4, 2]  =  1.0

julia> qr(A)
Base.SparseArrays.SPQR.QRSparse{Float64,Int64}
Q factor:
4×4 Base.SparseArrays.SPQR.QRSparseQ{Float64,Int64}:
 -0.707107   0.0        0.0       -0.707107
  0.0       -0.707107  -0.707107   0.0
  0.0       -0.707107   0.707107   0.0
 -0.707107   0.0        0.0        0.707107
R factor:
2×2 SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [1, 1]  =  -1.41421
  [2, 2]  =  -1.41421
Row permutation:
4-element Array{Int64,1}:
 1
 3
 4
 2
Column permutation:
2-element Array{Int64,1}:
 1
 2
```


In [48]:
F = qr(A)

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
5×5 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.563674    0.0466429   0.182406  -0.804224    0.00690442
 -0.0367436  -0.916424    0.333546   0.0500771   0.212264
 -0.59381    -0.155783   -0.113892   0.375449   -0.684973
 -0.361548    0.35938     0.656933   0.426306    0.356135
 -0.444515   -0.0675935  -0.641048   0.167384    0.599064
R factor:
3×3 Array{Float64,2}:
 -1.15375  -0.923066  -1.46644
  0.0      -0.905936   0.0451119
  0.0       0.0        0.422428

In [49]:
Q = F.Q

5×5 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.563674    0.0466429   0.182406  -0.804224    0.00690442
 -0.0367436  -0.916424    0.333546   0.0500771   0.212264
 -0.59381    -0.155783   -0.113892   0.375449   -0.684973
 -0.361548    0.35938     0.656933   0.426306    0.356135
 -0.444515   -0.0675935  -0.641048   0.167384    0.599064

In [50]:
Q'Q

5×5 Array{Float64,2}:
  1.0          -1.38778e-17   0.0           1.52656e-16  -5.55112e-17
 -1.38778e-17   1.0          -3.46945e-17  -1.73472e-17  -1.38778e-17
  0.0          -3.46945e-17   1.0          -6.93889e-17   0.0
  1.52656e-16  -1.73472e-17  -6.93889e-17   1.0           0.0
 -5.55112e-17  -1.38778e-17   0.0           0.0           1.0

In [51]:
R = F.R

3×3 Array{Float64,2}:
 -1.15375  -0.923066  -1.46644
  0.0      -0.905936   0.0451119
  0.0       0.0        0.422428

In [52]:
Q*R

5×3 Array{Float64,2}:
 0.650341   0.478053    0.905751
 0.0423931  0.864138    0.15344
 0.68511    0.689255    0.815647
 0.417137   0.00815743  0.823906
 0.512861   0.471553    0.378009

In [54]:
Q[:,1:3]

5×3 Array{Float64,2}:
 -0.563674    0.0466429   0.182406
 -0.0367436  -0.916424    0.333546
 -0.59381    -0.155783   -0.113892
 -0.361548    0.35938     0.656933
 -0.444515   -0.0675935  -0.641048

In [57]:
Q[:,1:3]*R

5×3 Array{Float64,2}:
 0.650341   0.478053    0.905751
 0.0423931  0.864138    0.15344
 0.68511    0.689255    0.815647
 0.417137   0.00815743  0.823906
 0.512861   0.471553    0.378009

In [53]:
A

5×3 Array{Float64,2}:
 0.650341   0.478053    0.905751
 0.0423931  0.864138    0.15344
 0.68511    0.689255    0.815647
 0.417137   0.00815743  0.823906
 0.512861   0.471553    0.378009

---

# Eigenvalue decomposition

In [58]:
A = Symmetric(rand(3,3))

3×3 Symmetric{Float64,Array{Float64,2}}:
 0.707878  0.856847  0.764471
 0.856847  0.239067  0.372003
 0.764471  0.372003  0.100968

In [59]:
?eigen

search: eigen eigen! Eigen GeneralizedEigen eigvecs leading_zeros leading_ones



```
eigen(A; permute::Bool=true, scale::Bool=true, sortby) -> Eigen
```

Computes the eigenvalue decomposition of `A`, returning an [`Eigen`](@ref) factorization object `F` which contains the eigenvalues in `F.values` and the eigenvectors in the columns of the matrix `F.vectors`. (The `k`th eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

The following functions are available for `Eigen` objects: [`inv`](@ref), [`det`](@ref), and [`isposdef`](@ref).

For general nonsymmetric matrices it is possible to specify how the matrix is balanced before the eigenvector calculation. The option `permute=true` permutes the matrix to become closer to upper triangular, and `scale=true` scales the matrix by its diagonal elements to make rows and columns more equal in norm. The default is `true` for both options.

By default, the eigenvalues and vectors are sorted lexicographically by `(real(λ),imag(λ))`. A different comparison function `by(λ)` can be passed to `sortby`, or you can pass `sortby=nothing` to leave the eigenvalues in an arbitrary order.   Some special matrix types (e.g. [`Diagonal`](@ref) or [`SymTridiagonal`](@ref)) may implement their own sorting convention and not accept a `sortby` keyword.

# Examples

```jldoctest
julia> F = eigen([1.0 0.0 0.0; 0.0 3.0 0.0; 0.0 0.0 18.0])
Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
3-element Array{Float64,1}:
  1.0
  3.0
 18.0
vectors:
3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> F.values
3-element Array{Float64,1}:
  1.0
  3.0
 18.0

julia> F.vectors
3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> vals, vecs = F; # destructuring via iteration

julia> vals == F.values && vecs == F.vectors
true
```

---

```
eigen(A, B) -> GeneralizedEigen
```

Computes the generalized eigenvalue decomposition of `A` and `B`, returning a [`GeneralizedEigen`](@ref) factorization object `F` which contains the generalized eigenvalues in `F.values` and the generalized eigenvectors in the columns of the matrix `F.vectors`. (The `k`th generalized eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

Any keyword arguments passed to `eigen` are passed through to the lower-level [`eigen!`](@ref) function.

# Examples

```jldoctest
julia> A = [1 0; 0 -1]
2×2 Array{Int64,2}:
 1   0
 0  -1

julia> B = [0 1; 1 0]
2×2 Array{Int64,2}:
 0  1
 1  0

julia> F = eigen(A, B);

julia> F.values
2-element Array{Complex{Float64},1}:
 0.0 - 1.0im
 0.0 + 1.0im

julia> F.vectors
2×2 Array{Complex{Float64},2}:
  0.0+1.0im   0.0-1.0im
 -1.0+0.0im  -1.0-0.0im

julia> vals, vecs = F; # destructuring via iteration

julia> vals == F.values && vecs == F.vectors
true
```

---

```
eigen(A::Union{SymTridiagonal, Hermitian, Symmetric}, irange::UnitRange) -> Eigen
```

Computes the eigenvalue decomposition of `A`, returning an [`Eigen`](@ref) factorization object `F` which contains the eigenvalues in `F.values` and the eigenvectors in the columns of the matrix `F.vectors`. (The `k`th eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

The following functions are available for `Eigen` objects: [`inv`](@ref), [`det`](@ref), and [`isposdef`](@ref).

The [`UnitRange`](@ref) `irange` specifies indices of the sorted eigenvalues to search for.

!!! note
    If `irange` is not `1:n`, where `n` is the dimension of `A`, then the returned factorization will be a *truncated* factorization.


---

```
eigen(A::Union{SymTridiagonal, Hermitian, Symmetric}, vl::Real, vu::Real) -> Eigen
```

Computes the eigenvalue decomposition of `A`, returning an [`Eigen`](@ref) factorization object `F` which contains the eigenvalues in `F.values` and the eigenvectors in the columns of the matrix `F.vectors`. (The `k`th eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

The following functions are available for `Eigen` objects: [`inv`](@ref), [`det`](@ref), and [`isposdef`](@ref).

`vl` is the lower bound of the window of eigenvalues to search for, and `vu` is the upper bound.

!!! note
    If [`vl`, `vu`] does not contain all eigenvalues of `A`, then the returned factorization will be a *truncated* factorization.



In [60]:
F = eigen(A)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
3-element Array{Float64,1}:
 -0.524606217687557
 -0.2064125183060615
  1.778931648745433
vectors:
3×3 Array{Float64,2}:
  0.680423   0.0479872  -0.731247
 -0.504551  -0.692996   -0.514961
 -0.531462   0.719343   -0.447318

In [61]:
Q = F.vectors

3×3 Array{Float64,2}:
  0.680423   0.0479872  -0.731247
 -0.504551  -0.692996   -0.514961
 -0.531462   0.719343   -0.447318

In [63]:
Λ = Diagonal(F.values)

3×3 Diagonal{Float64,Array{Float64,1}}:
 -0.524606    ⋅         ⋅ 
   ⋅        -0.206413   ⋅ 
   ⋅          ⋅        1.77893

In [64]:
A*Q - Q*Λ

3×3 Array{Float64,2}:
 1.11022e-16  7.07767e-16  -2.22045e-15
 5.55112e-17  4.44089e-16  -7.77156e-16
 5.55112e-17  3.60822e-16  -1.77636e-15

In [65]:
Q*Λ*Q'

3×3 Array{Float64,2}:
 0.707878  0.856847  0.764471
 0.856847  0.239067  0.372003
 0.764471  0.372003  0.100968

In [66]:
A

3×3 Symmetric{Float64,Array{Float64,2}}:
 0.707878  0.856847  0.764471
 0.856847  0.239067  0.372003
 0.764471  0.372003  0.100968

In [69]:
A = randn(3,3)

3×3 Array{Float64,2}:
 -0.126716   1.07454   -1.4429
 -0.680092  -0.377948   0.161127
  0.119797  -0.458158  -0.49786

In [70]:
F = eigen(A)

Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}}
values:
3-element Array{Complex{Float64},1}:
 -0.7997089733068946 + 0.0im
 -0.1014073535634013 - 1.0507770291696472im
 -0.1014073535634013 + 1.0507770291696472im
vectors:
3×3 Array{Complex{Float64},2}:
 0.504329+0.0im  -0.809684-0.0im       -0.809684+0.0im
 0.563149+0.0im    0.16515+0.501623im    0.16515-0.501623im
 0.654611+0.0im   0.137191-0.21608im    0.137191+0.21608im

In [71]:
X = F.vectors

3×3 Array{Complex{Float64},2}:
 0.504329+0.0im  -0.809684-0.0im       -0.809684+0.0im
 0.563149+0.0im    0.16515+0.501623im    0.16515-0.501623im
 0.654611+0.0im   0.137191-0.21608im    0.137191+0.21608im

In [72]:
Λ = Diagonal(F.values)

3×3 Diagonal{Complex{Float64},Array{Complex{Float64},1}}:
 -0.799709+0.0im            ⋅                    ⋅    
           ⋅      -0.101407-1.05078im            ⋅    
           ⋅                ⋅          -0.101407+1.05078im

In [73]:
A*X - X*Λ

3×3 Array{Complex{Float64},2}:
 5.55112e-17+0.0im   5.55112e-17+6.66134e-16im   5.55112e-17-6.66134e-16im
 5.55112e-17+0.0im  -3.33067e-16+2.498e-16im    -3.33067e-16-2.498e-16im
 1.11022e-16+0.0im   1.66533e-16-2.91434e-16im   1.66533e-16+2.91434e-16im

In [74]:
X*Λ*inv(X)

3×3 Array{Complex{Float64},2}:
 -0.126716+2.22045e-16im    1.07454-4.16334e-17im   -1.4429-2.22045e-16im
 -0.680092+0.0im          -0.377948-1.11022e-16im  0.161127+5.55112e-17im
  0.119797-5.55112e-17im  -0.458158+5.55112e-17im  -0.49786+0.0im

In [75]:
(X*Λ)/X

3×3 Array{Complex{Float64},2}:
 -0.126716+0.0im            1.07454-0.0im   -1.4429+0.0im
 -0.680092+0.0im          -0.377948+0.0im  0.161127-0.0im
  0.119797+1.71398e-17im  -0.458158+0.0im  -0.49786+0.0im

In [76]:
A

3×3 Array{Float64,2}:
 -0.126716   1.07454   -1.4429
 -0.680092  -0.377948   0.161127
  0.119797  -0.458158  -0.49786

---

# SVD

In [77]:
A = randn(5,3)

5×3 Array{Float64,2}:
 -0.906125   1.2299    -0.466516
 -0.504557  -1.23466    0.0529272
  1.55797   -1.16075   -0.518231
  0.679285  -0.685737   0.665426
 -0.15268    0.450566  -1.50688

In [78]:
?svd

search: svd svd! SVD svdvals svdvals! GeneralizedSVD isvalid CholeskyPivoted



```
svd(A; full::Bool = false, alg::Algorithm = default_svd_alg(A)) -> SVD
```

Compute the singular value decomposition (SVD) of `A` and return an `SVD` object.

`U`, `S`, `V` and `Vt` can be obtained from the factorization `F` with `F.U`, `F.S`, `F.V` and `F.Vt`, such that `A = U * Diagonal(S) * Vt`. The algorithm produces `Vt` and hence `Vt` is more efficient to extract than `V`. The singular values in `S` are sorted in descending order.

Iterating the decomposition produces the components `U`, `S`, and `V`.

If `full = false` (default), a "thin" SVD is returned. For a $M \times N$ matrix `A`, in the full factorization `U` is `M \times M` and `V` is `N \times N`, while in the thin factorization `U` is `M \times K` and `V` is `N \times K`, where `K = \min(M,N)` is the number of singular values.

If `alg = DivideAndConquer()` a divide-and-conquer algorithm is used to calculate the SVD. Another (typically slower but more accurate) option is `alg = QRIteration()`.

!!! compat "Julia 1.3"
    The `alg` keyword argument requires Julia 1.3 or later.


# Examples

```jldoctest
julia> A = rand(4,3);

julia> F = svd(A); # Store the Factorization Object

julia> A ≈ F.U * Diagonal(F.S) * F.Vt
true

julia> U, S, V = F; # destructuring via iteration

julia> A ≈ U * Diagonal(S) * V'
true

julia> Uonly, = svd(A); # Store U only

julia> Uonly == U
true
```

---

```
svd(A, B) -> GeneralizedSVD
```

Compute the generalized SVD of `A` and `B`, returning a `GeneralizedSVD` factorization object `F` such that `[A;B] = [F.U * F.D1; F.V * F.D2] * F.R0 * F.Q'`

  * `U` is a M-by-M orthogonal matrix,
  * `V` is a P-by-P orthogonal matrix,
  * `Q` is a N-by-N orthogonal matrix,
  * `D1` is a M-by-(K+L) diagonal matrix with 1s in the first K entries,
  * `D2` is a P-by-(K+L) matrix whose top right L-by-L block is diagonal,
  * `R0` is a (K+L)-by-N matrix whose rightmost (K+L)-by-(K+L) block is          nonsingular upper block triangular,

`K+L` is the effective numerical rank of the matrix `[A; B]`.

Iterating the decomposition produces the components `U`, `V`, `Q`, `D1`, `D2`, and `R0`.

The generalized SVD is used in applications such as when one wants to compare how much belongs to `A` vs. how much belongs to `B`, as in human vs yeast genome, or signal vs noise, or between clusters vs within clusters. (See Edelman and Wang for discussion: https://arxiv.org/abs/1901.00485)

It decomposes `[A; B]` into `[UC; VS]H`, where `[UC; VS]` is a natural orthogonal basis for the column space of `[A; B]`, and `H = RQ'` is a natural non-orthogonal basis for the rowspace of `[A;B]`, where the top rows are most closely attributed to the `A` matrix, and the bottom to the `B` matrix. The multi-cosine/sine matrices `C` and `S` provide a multi-measure of how much `A` vs how much `B`, and `U` and `V` provide directions in which these are measured.

# Examples

```jldoctest
julia> A = randn(3,2); B=randn(4,2);

julia> F = svd(A, B);

julia> U,V,Q,C,S,R = F;

julia> H = R*Q';

julia> [A; B] ≈ [U*C; V*S]*H
true

julia> [A; B] ≈ [F.U*F.D1; F.V*F.D2]*F.R0*F.Q'
true

julia> Uonly, = svd(A,B);

julia> U == Uonly
true
```


In [79]:
F = svd(A)

SVD{Float64,Float64,Array{Float64,2}}
U factor:
5×3 Array{Float64,2}:
 -0.57549   -0.0593737   0.0164534
  0.233998   0.166257   -0.937594
  0.614462  -0.599628    0.125886
  0.393425   0.203207    0.200371
 -0.285848  -0.753649   -0.254265
singular values:
3-element Array{Float64,1}:
 2.769313212577829
 1.7685726217665514
 1.2044994865302334
Vt factor:
3×3 Array{Float64,2}:
  0.603618  -0.761387   0.236506
 -0.402126  -0.0345993  0.91493
  0.688433   0.647374   0.327058

In [81]:
F = svd(A, full=true)

SVD{Float64,Float64,Array{Float64,2}}
U factor:
5×5 Array{Float64,2}:
 -0.57549   -0.0593737   0.0164534  0.529192   -0.62046
  0.233998   0.166257   -0.937594   0.132318   -0.144957
  0.614462  -0.599628    0.125886   0.0145312  -0.496815
  0.393425   0.203207    0.200371   0.814838    0.315934
 -0.285848  -0.753649   -0.254265   0.195643    0.497371
singular values:
3-element Array{Float64,1}:
 2.769313212577829
 1.7685726217665514
 1.2044994865302334
Vt factor:
3×3 Array{Float64,2}:
  0.603618  -0.761387   0.236506
 -0.402126  -0.0345993  0.91493
  0.688433   0.647374   0.327058

In [82]:
U = F.U

5×5 Array{Float64,2}:
 -0.57549   -0.0593737   0.0164534  0.529192   -0.62046
  0.233998   0.166257   -0.937594   0.132318   -0.144957
  0.614462  -0.599628    0.125886   0.0145312  -0.496815
  0.393425   0.203207    0.200371   0.814838    0.315934
 -0.285848  -0.753649   -0.254265   0.195643    0.497371

In [87]:
Σ = diagm(5, 3, F.S)

5×3 Array{Float64,2}:
 2.76931  0.0      0.0
 0.0      1.76857  0.0
 0.0      0.0      1.2045
 0.0      0.0      0.0
 0.0      0.0      0.0

In [88]:
V = F.V

3×3 Adjoint{Float64,Array{Float64,2}}:
  0.603618  -0.402126   0.688433
 -0.761387  -0.0345993  0.647374
  0.236506   0.91493    0.327058

In [89]:
U*Σ*V'

5×3 Array{Float64,2}:
 -0.906125   1.2299    -0.466516
 -0.504557  -1.23466    0.0529272
  1.55797   -1.16075   -0.518231
  0.679285  -0.685737   0.665426
 -0.15268    0.450566  -1.50688

In [90]:
A

5×3 Array{Float64,2}:
 -0.906125   1.2299    -0.466516
 -0.504557  -1.23466    0.0529272
  1.55797   -1.16075   -0.518231
  0.679285  -0.685737   0.665426
 -0.15268    0.450566  -1.50688

In [92]:
σ = F.S

3-element Array{Float64,1}:
 2.769313212577829
 1.7685726217665514
 1.2044994865302334

In [95]:
σ[1]*U[:,1]*V[:,1]'

5×3 Array{Float64,2}:
 -0.961994   1.21343   -0.376923
  0.391153  -0.493389   0.153259
  1.02714   -1.2956     0.402448
  0.657653  -0.829545   0.257678
 -0.477825   0.602715  -0.187219

In [96]:
σ[1]*U[:,1]*V[:,1]' + σ[2]*U[:,2]*V[:,2]'

5×3 Array{Float64,2}:
 -0.919768    1.21707   -0.472997
  0.272913   -0.503563   0.422284
  1.45359    -1.25891   -0.567823
  0.513134   -0.841979   0.586491
  0.0581612   0.648832  -1.40671

In [97]:
A

5×3 Array{Float64,2}:
 -0.906125   1.2299    -0.466516
 -0.504557  -1.23466    0.0529272
  1.55797   -1.16075   -0.518231
  0.679285  -0.685737   0.665426
 -0.15268    0.450566  -1.50688

---